# analysis_options.yaml

include: package:lints/recommended.yaml

analyzer:
  # Enable stricter type inference
  language:
    strict-inference: true

  # Treat missing docs as warnings (optional)
  errors:
    public_member_api_docs: warning
    always_declare_return_types: warning

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # ─── Style & Readability ────────────────────────────────────────────────────
    always_declare_return_types: true
    always_specify_types: true
    annotate_overrides: true
    slash_for_doc_comments: true
    file_names: true
    directives_ordering: true
    library_prefixes: true

    # ─── Code Safety & Null-safety ─────────────────────────────────────────────
    avoid_empty_else: true
    avoid_returning_null: true
    avoid_null_checks_in_equality_operators: true
    prefer_null_aware_operators: true
    prefer_if_null_operators: true

    # ─── Performance & Best Practices ─────────────────────────────────────────
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_function_type_syntax_for_parameters: true
    control_flow_in_finally: true

    # ─── Naming ────────────────────────────────────────────────────────────────
    camel_case_types: true
    constant_identifier_names: true

 
